#!/usr/bin/env python3
"""
Fetch Keycloak SAML IdP metadata and write SonarQube sonar.properties (SAML + base URL).
Idempotent: overwrites the output file each run.
"""

from __future__ import annotations

import os
import sys
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET
from urllib.parse import urlparse

SAML_NS = "urn:oasis:names:tc:SAML:2.0:metadata"
DS_NS = "http://www.w3.org/2000/09/xmldsig#"
ET.register_namespace("", SAML_NS)


def _req(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        print(f"[ERROR] Missing required env: {name}", file=sys.stderr)
        sys.exit(1)
    return value


def _fetch_metadata(url: str) -> bytes:
    print(f"[INFO] Fetching IdP metadata from {url}")
    req = urllib.request.Request(url, headers={"User-Agent": "sonarqube-config-init/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def _parse_metadata(xml_bytes: bytes) -> tuple[str, str, str]:
    root = ET.fromstring(xml_bytes)
    entity_id = root.attrib.get("entityID", "").strip()
    if not entity_id:
        raise ValueError("entityID not found in IdP metadata")

    sso_url = ""
    for el in root.iter(f"{{{SAML_NS}}}SingleSignOnService"):
        binding = el.attrib.get("Binding", "")
        if "HTTP-Redirect" in binding or "HTTP-POST" in binding:
            sso_url = el.attrib.get("Location", "").strip()
            if sso_url:
                break
    if not sso_url:
        raise ValueError("SingleSignOnService Location not found in IdP metadata")

    cert = ""
    for el in root.iter(f"{{{DS_NS}}}X509Certificate"):
        text = (el.text or "").strip()
        if text:
            cert = "".join(text.split())
            break
    if not cert:
        raise ValueError("X509Certificate not found in IdP metadata")

    return entity_id, sso_url, cert


def _validate_external_url(sonar_base: str) -> None:
    domain = os.environ.get("SONARQUBE_DOMAIN", "").strip()
    if not domain:
        return
    ext_host = urlparse(sonar_base).netloc
    if ext_host != domain:
        print(
            f"[ERROR] SONARQUBE_EXTERNAL_URL host '{ext_host}' "
            f"does not match SONARQUBE_DOMAIN '{domain}'.",
            file=sys.stderr,
        )
        sys.exit(1)
    if urlparse(sonar_base).scheme != "https":
        print("[ERROR] SONARQUBE_EXTERNAL_URL must use https://.", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    keycloak_base = _req("KEYCLOAK_BASE_URL").rstrip("/")
    realm = _req("KC_REALM")
    sonar_base = _req("SONARQUBE_EXTERNAL_URL").rstrip("/")
    _validate_external_url(sonar_base)
    application_id = os.environ.get("SONAR_SAML_APPLICATION_ID", "sonarqube").strip()
    provider_name = os.environ.get("SONAR_SAML_PROVIDER_NAME", "Keycloak").strip()
    output = _req("SONAR_PROPERTIES_OUTPUT")

    metadata_url = f"{keycloak_base}/realms/{realm}/protocol/saml/descriptor"
    entity_id, login_url, certificate = _parse_metadata(_fetch_metadata(metadata_url))

    lines = [
        "# Generated by sonarqube-config-init — do not edit by hand.",
        f"sonar.core.serverBaseURL={sonar_base}",
        "sonar.auth.saml.enabled=true",
        f"sonar.auth.saml.applicationId={application_id}",
        f"sonar.auth.saml.providerName={provider_name}",
        f"sonar.auth.saml.providerId={entity_id}",
        f"sonar.auth.saml.loginUrl={login_url}",
        f"sonar.auth.saml.certificate.secured={certificate}",
        "sonar.auth.saml.user.login=login",
        # Keycloak sonarqube client maps username → login; no separate "name" mapper by default.
        "sonar.auth.saml.user.name=login",
        "sonar.auth.saml.user.email=email",
        "sonar.auth.saml.group.name=groups",
        # false = Sonar does not sign authn requests (no SP key/cert required).
        # Keycloak client must also disable assertion/response signing (see 09_sonarqube_sso.md).
        "sonar.auth.saml.signature.enabled=false",
        "",
    ]

    os.makedirs(os.path.dirname(output) or ".", exist_ok=True)
    with open(output, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print(f"[INFO] Wrote Sonar properties to {output}")


if __name__ == "__main__":
    main()
