import { DEPLOY_TARGETS_CI_PATH } from './deploy.constants';
import { deployRefVariableName, isTemplateBuiltinTarget } from './deploy-target.util';

import type { DeploymentTarget } from '../schemas/project.schema';

/**
 * Generates `.dsoaas/deploy-targets.gitlab-ci.yml` with one job per non-standard target.
 * Standard dev/stg/prod jobs remain in the shared auto-devops-pipeline template.
 */
export function generateDeployTargetsCiYaml(targets: DeploymentTarget[]): string {
  const extra = targets.filter((t) => !isTemplateBuiltinTarget(t.key));
  if (extra.length === 0) {
    return '';
  }

  const lines: string[] = [
    '# Generated by the DSOaaS Management API — do not edit by hand.',
    '# Update targets via upsertDeploymentTarget / removeDeploymentTarget.',
    '',
  ];

  for (const target of extra) {
    const refVar = deployRefVariableName(target.key);
    const when = target.key === 'prod' || target.key.startsWith('prod-') ? 'manual' : 'on_success';
    lines.push(
      `deploy:${target.key}:`,
      '  extends: .deploy-helm',
      '  variables:',
      `    DEPLOY_ENV: ${target.key}`,
      '  environment:',
      `    name: ${target.gitlabEnvironment ?? target.key}`,
      '    url: https://$APP_HOST',
      '  rules:',
      `    - if: '$${refVar} == "none"'`,
      '      when: never',
      `    - if: '$CI_COMMIT_BRANCH == $${refVar}'`,
      `      when: ${when}`,
      '',
    );
  }

  return lines.join('\n');
}

const DSOAAS_INCLUDE_MARKER = '.dsoaas/deploy-targets.gitlab-ci.yml';

/**
 * Merges Auto DevOps pipeline include and optional local deploy-targets fragment
 * into project `.gitlab-ci.yml` content.
 */
export function buildGitlabCiWithIncludes(
  pipelineProject: string,
  pipelineFile: string,
  hasExtraTargets: boolean,
): string {
  const lines = [
    '# Managed by DSOaaS — Auto DevOps pipeline include',
    'include:',
    `  - project: ${pipelineProject}`,
    `    file: ${pipelineFile}`,
  ];

  if (hasExtraTargets) {
    lines.push(
      `  - local: ${DSOAAS_INCLUDE_MARKER}`,
      '    rules:',
      '      - exists:',
      `          - ${DSOAAS_INCLUDE_MARKER}`,
    );
  }

  lines.push('');
  return lines.join('\n');
}

export { DEPLOY_TARGETS_CI_PATH };
