import { BUILD_JOBS_CI_PATH, DEPLOY_TARGETS_CI_PATH } from './deploy.constants';

import { deployRefVariableName, isTemplateBuiltinTarget } from './deploy-target.util';

import { appEnvironmentScope, resolveDockerfile, targetUsesPerAppDeploy } from './target-app.util';

import type { DeploymentTarget } from '../schemas/project.schema';

function deployJobWhen(targetKey: string): string {
  return targetKey === 'prod' || targetKey.startsWith('prod-') ? 'manual' : 'on_success';
}

function buildDisableBuiltinLines(disabledBuiltins: Set<string>): string[] {
  if (disabledBuiltins.size === 0) {
    return [];
  }

  const lines: string[] = [
    '# Disable template built-in deploy jobs when per-app jobs are defined for this target.',

    '',
  ];

  for (const key of [...disabledBuiltins].sort()) {
    lines.push(`deploy:${key}:`, '  rules:', '    - when: never', '');
  }

  return lines;
}

/**
 * Generates `.dsoaas/deploy-targets.gitlab-ci.yml` with per-app deploy jobs and optional built-in overrides.
 */
export function generateDeployTargetsCiYaml(targets: DeploymentTarget[]): string {
  const header: string[] = [
    '# Generated by the DSOaaS Management API — do not edit by hand.',
    '# Update targets via upsertDeploymentTarget / removeDeploymentTarget.',
    '',
  ];

  const jobLines: string[] = [];

  let wroteJob = false;

  const disabledBuiltins = new Set<string>();

  for (const target of targets) {
    if (!target.enabled || target.deployRef === 'none') {
      continue;
    }

    const refVar = deployRefVariableName(target.key);

    const when = deployJobWhen(target.key);

    if (targetUsesPerAppDeploy(target) && target.apps?.length) {
      if (isTemplateBuiltinTarget(target.key)) {
        disabledBuiltins.add(target.key);
      }

      for (const app of target.apps) {
        const jobKey = `${target.key}-${app.name}`;

        jobLines.push(
          `deploy:${jobKey}:`,

          '  extends: .deploy-helm',

          `  resource_group: deploy-${target.key}`,

          '  variables:',

          `    DEPLOY_ENV: ${target.key}`,

          '  environment:',

          // Must match appEnvironmentScope() so env-scoped CI vars (KUBECONFIG_B64, etc.) apply.
          `    name: ${appEnvironmentScope(target.key, app.name)}`,

          '    url: https://$APP_HOST',

          '  rules:',

          `    - if: '$${refVar} == "none"'`,

          '      when: never',

          `    - if: '$CI_COMMIT_BRANCH == $${refVar}'`,

          `      when: ${when}`,

          '',
        );

        wroteJob = true;
      }

      continue;
    }

    if (!isTemplateBuiltinTarget(target.key)) {
      jobLines.push(
        `deploy:${target.key}:`,

        '  extends: .deploy-helm',

        '  variables:',

        `    DEPLOY_ENV: ${target.key}`,

        '  environment:',

        `    name: ${target.gitlabEnvironment ?? target.key}`,

        '    url: https://$APP_HOST',

        '  rules:',

        `    - if: '$${refVar} == "none"'`,

        '      when: never',

        `    - if: '$CI_COMMIT_BRANCH == $${refVar}'`,

        `      when: ${when}`,

        '',
      );

      wroteJob = true;
    }
  }

  if (!wroteJob && disabledBuiltins.size === 0) {
    return '';
  }

  return [...header, ...buildDisableBuiltinLines(disabledBuiltins), ...jobLines].join('\n');
}

/**

 * Generates `.dsoaas/build-jobs.gitlab-ci.yml` with per-app Kaniko jobs.

 */

export function generateBuildJobsCiYaml(targets: DeploymentTarget[]): string {
  const jobs: string[] = [];
  /** One Kaniko job per image suffix across all targets (dev/stg/prod often share the same app). */
  const seenImages = new Set<string>();

  for (const target of targets) {
    if (!target.apps?.length) {
      continue;
    }

    for (const app of target.apps) {
      if (seenImages.has(app.image)) {
        continue;
      }
      seenImages.add(app.image);

      const dockerfile = resolveDockerfile(app.dockerfile);

      jobs.push(
        `build:${app.image}:`,

        '  extends: .build-kaniko',

        '  variables:',

        `    KANIKO_DOCKERFILE: "${dockerfile}"`,

        `    KANIKO_IMAGE_NAME: "${app.image}"`,

        '',
      );
    }
  }

  if (jobs.length === 0) {
    return '';
  }

  return [
    '# Generated by the DSOaaS Management API — do not edit by hand.',

    '# Update deployment targets in the operator console.',

    '',

    'build:',

    '  rules:',

    '    - when: never',

    '',

    ...jobs,
  ].join('\n');
}

export function projectNeedsDeployTargetsFragment(targets: DeploymentTarget[]): boolean {
  return generateDeployTargetsCiYaml(targets).length > 0;
}

export function projectNeedsBuildJobsFragment(targets: DeploymentTarget[]): boolean {
  return generateBuildJobsCiYaml(targets).length > 0;
}

const DSOAAS_DEPLOY_MARKER = DEPLOY_TARGETS_CI_PATH;

const DSOAAS_BUILD_MARKER = BUILD_JOBS_CI_PATH;

/**

 * Builds managed `include` entries for root `.gitlab-ci.yml`.

 */

export function buildManagedIncludes(
  pipelineProject: string,

  pipelineFile: string,

  targets: DeploymentTarget[],
): Array<Record<string, unknown>> {
  const includes: Array<Record<string, unknown>> = [
    { project: pipelineProject, file: pipelineFile },
  ];

  if (projectNeedsDeployTargetsFragment(targets)) {
    includes.push({
      local: DSOAAS_DEPLOY_MARKER,

      rules: [{ exists: [DSOAAS_DEPLOY_MARKER] }],
    });
  }

  if (projectNeedsBuildJobsFragment(targets)) {
    includes.push({
      local: DSOAAS_BUILD_MARKER,

      rules: [{ exists: [DSOAAS_BUILD_MARKER] }],
    });
  }

  return includes;
}

/**

 * @deprecated Use mergeProjectGitlabCi for root file writes.

 */

export function buildGitlabCiWithIncludes(
  pipelineProject: string,

  pipelineFile: string,

  hasExtraTargets: boolean,
): string {
  const includes: Array<Record<string, unknown>> = [
    { project: pipelineProject, file: pipelineFile },
  ];

  if (hasExtraTargets) {
    includes.push({
      local: DSOAAS_DEPLOY_MARKER,

      rules: [{ exists: [DSOAAS_DEPLOY_MARKER] }],
    });
  }

  return [
    '# Managed by DSOaaS — Auto DevOps pipeline include',

    'include:',

    ...includes.map(
      (inc) =>
        `  - project: ${(inc as { project: string }).project}\n    file: ${(inc as { file: string }).file}`,
    ),

    '',
  ].join('\n');
}

export { DEPLOY_TARGETS_CI_PATH, BUILD_JOBS_CI_PATH };
