/**
 * Type-safe application configuration loaded from environment variables.
 *
 * Required env vars are validated at startup — the app will fail to start
 * if any required variable is missing.
 *
 * @returns AppConfiguration object consumed via NestJS ConfigService
 */
export interface AppConfiguration {
  port: number;
  host: string;
  domain: string;
  appsDomain: string;
  gitlabDomain: string;
  apiKey?: string;
  logLevel: string;

  gitlab: {
    url: string;
    token: string;
    templateGroupId: number;
    configGroupId: number;
  };

  mongo: {
    /** Full MongoDB connection URI (e.g. mongodb://mongo:27017) */
    url: string;
    /** Database name (e.g. platform) */
    dbName: string;
  };

  vault: {
    url: string;
    token: string;
  };

  kube: {
    /**
     * Internal URL of the k3d API server, reachable from within devops-network
     * (e.g. https://k3d-dsoaas-server-0:6443). Used when the API needs to
     * interact directly with the cluster; optional since kubeconfigs contain
     * their own server URLs.
     */
    apiUrl?: string;
    /**
     * Host directory where per-env kubeconfigs are stored (dev.yaml, stg.yaml,
     * prod.yaml). Generated by bootstrap/runner-rbac.sh and mounted read-only
     * into the api container at /etc/dsoaas/kubeconfigs.
     */
    configDir: string;
  };

  autoDevops: {
    /**
     * GitLab project path of the shared Auto DevOps pipeline template.
     * Defaults to "configs/auto-devops-pipeline". Override via
     * AUTO_DEVOPS_PIPELINE_PROJECT env var.
     */
    pipelineProject: string;
    /**
     * Path to the CI file within the pipeline template project.
     * Defaults to "/.gitlab-ci.yml". Override via
     * AUTO_DEVOPS_PIPELINE_FILE env var.
     */
    pipelineFile: string;
  };

  oidc: {
    issuerUrl?: string;
    jwksUrl?: string;
    audience?: string;
  };
}

const configuration = (): AppConfiguration => {
  const required = (key: string): string => {
    const value = process.env[key];
    if (!value) {
      throw new Error(`Missing required environment variable: ${key}`);
    }
    return value;
  };

  const optional = (key: string): string | undefined => process.env[key];

  const domain = required('DOMAIN');

  return {
    port: Number.parseInt(optional('API_PORT') ?? '3000', 10),
    host: optional('API_HOST') ?? '0.0.0.0',
    domain,
    appsDomain: optional('APPS_DOMAIN') ?? `apps.${domain}`,
    gitlabDomain: optional('GITLAB_DOMAIN') ?? `gitlab.devops.${domain}`,
    apiKey: optional('API_KEY'),
    logLevel: optional('LOG_LEVEL') ?? 'info',

    gitlab: {
      url: optional('GITLAB_URL') ?? 'http://gitlab',
      token: required('GITLAB_ROOT_TOKEN'),
      templateGroupId: Number.parseInt(required('GITLAB_TEMPLATE_GROUP_ID'), 10),
      configGroupId: Number.parseInt(required('GITLAB_CONFIG_GROUP_ID'), 10),
    },

    mongo: {
      url: optional('MONGO_URL') ?? 'mongodb://mongo:27017',
      dbName: optional('MONGO_DB_NAME') ?? 'platform',
    },

    vault: {
      url: optional('VAULT_URL') ?? 'http://vault:8200',
      token: required('VAULT_DEV_ROOT_TOKEN_ID'),
    },

    kube: {
      apiUrl: optional('KUBE_API_INTERNAL_URL'),
      configDir: optional('KUBECONFIG_DIR') ?? '/etc/dsoaas/kubeconfigs',
    },

    autoDevops: {
      pipelineProject:
        optional('AUTO_DEVOPS_PIPELINE_PROJECT') ??
        'system/devsecops-platform/configs/auto-devops-pipeline',
      pipelineFile: optional('AUTO_DEVOPS_PIPELINE_FILE') ?? '.gitlab-ci.yml',
    },

    oidc: {
      issuerUrl: optional('OIDC_ISSUER_URL'),
      jwksUrl: optional('OIDC_JWKS_URL'),
      audience: optional('OIDC_AUDIENCE'),
    },
  };
};

export default configuration;
